<?php

use App\Event;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();
        Event::insert([
            [
                'id' => 1,
                'gym_id' => 7,
                'name' => 'Vault',
                'abbrev' => 'VT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'gym_id' => 7,
                'name' => 'Bars',
                'abbrev' => 'UB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'gym_id' => 7,
                'name' => 'Beam',
                'abbrev' => 'BB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'gym_id' => 7,
                'name' => 'Floor',
                'abbrev' => 'FX',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'gym_id' => 7,
                'name' => 'Pommel',
                'abbrev' => 'PH',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'gym_id' => 7,
                'name' => 'Rings',
                'abbrev' => 'SR',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'gym_id' => 7,
                'name' => 'PBars',
                'abbrev' => 'PB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'gym_id' => 7,
                'name' => 'HBar',
                'abbrev' => 'HB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'gym_id' => 7,
                'name' => 'Conditioning',
                'abbrev' => 'CD',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'gym_id' => 7,
                'name' => 'Trampoline',
                'abbrev' => 'TP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'gym_id' => 7,
                'name' => 'Tumbling',
                'abbrev' => 'TB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'gym_id' => 7,
                'name' => 'Stunting',
                'abbrev' => 'ST',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'gym_id' => 7,
                'name' => 'Double Mini',
                'abbrev' => 'DM',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'gym_id' => 7,
                'name' => 'Power Tumbling',
                'abbrev' => 'PT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'gym_id' => 7,
                'name' => 'Motions',
                'abbrev' => 'MO',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'gym_id' => 7,
                'name' => 'Jumps',
                'abbrev' => 'JP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'gym_id' => 7,
                'name' => 'Locomotor',
                'abbrev' => 'LO',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'gym_id' => 7,
                'name' => 'Warm Up',
                'abbrev' => 'WU',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'gym_id' => 7,
                'name' => 'Physical Abilities',
                'abbrev' => 'PA',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'gym_id' => 4,
                'name' => 'Vault',
                'abbrev' => 'VT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'gym_id' => 4,
                'name' => 'Bars',
                'abbrev' => 'UB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'gym_id' => 4,
                'name' => 'Beam',
                'abbrev' => 'BB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'gym_id' => 4,
                'name' => 'Floor',
                'abbrev' => 'FX',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'gym_id' => 4,
                'name' => 'Pommel',
                'abbrev' => 'PH',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'gym_id' => 4,
                'name' => 'Rings',
                'abbrev' => 'SR',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'gym_id' => 4,
                'name' => 'PBars',
                'abbrev' => 'PB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'gym_id' => 4,
                'name' => 'HBar',
                'abbrev' => 'HB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'gym_id' => 4,
                'name' => 'Conditioning',
                'abbrev' => 'CD',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'gym_id' => 4,
                'name' => 'Trampoline',
                'abbrev' => 'TP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'gym_id' => 4,
                'name' => 'Tumbling',
                'abbrev' => 'TB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'gym_id' => 4,
                'name' => 'Stunting',
                'abbrev' => 'ST',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'gym_id' => 4,
                'name' => 'Double Mini',
                'abbrev' => 'DM',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'gym_id' => 4,
                'name' => 'Power Tumbling',
                'abbrev' => 'PT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'gym_id' => 6,
                'name' => 'Vault',
                'abbrev' => 'VT',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'gym_id' => 6,
                'name' => 'Bars',
                'abbrev' => 'UB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'gym_id' => 6,
                'name' => 'Beam',
                'abbrev' => 'BB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'gym_id' => 6,
                'name' => 'Floor',
                'abbrev' => 'FX',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'gym_id' => 6,
                'name' => 'Pommel',
                'abbrev' => 'PH',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'gym_id' => 6,
                'name' => 'Rings',
                'abbrev' => 'SR',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'gym_id' => 6,
                'name' => 'PBars',
                'abbrev' => 'PB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'gym_id' => 6,
                'name' => 'HBar',
                'abbrev' => 'HB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'gym_id' => 6,
                'name' => 'Conditioning',
                'abbrev' => 'CD',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'gym_id' => 6,
                'name' => 'Trampoline',
                'abbrev' => 'TP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'gym_id' => 6,
                'name' => 'Tumbling',
                'abbrev' => 'TB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'gym_id' => 6,
                'name' => 'Stunting',
                'abbrev' => 'ST',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'gym_id' => 6,
                'name' => 'Double Mini',
                'abbrev' => 'DM',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'gym_id' => 6,
                'name' => 'Power Tumbling',
                'abbrev' => 'PT',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'gym_id' => 8,
                'name' => 'Vault',
                'abbrev' => 'VT',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'gym_id' => 8,
                'name' => 'Bars',
                'abbrev' => 'UB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'gym_id' => 8,
                'name' => 'Beam',
                'abbrev' => 'BB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 51,
                'gym_id' => 8,
                'name' => 'Floor',
                'abbrev' => 'FX',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'gym_id' => 8,
                'name' => 'Pommel',
                'abbrev' => 'PH',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'gym_id' => 8,
                'name' => 'Rings',
                'abbrev' => 'SR',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'gym_id' => 8,
                'name' => 'PBars',
                'abbrev' => 'PB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'gym_id' => 8,
                'name' => 'HBar',
                'abbrev' => 'HB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'gym_id' => 8,
                'name' => 'Conditioning',
                'abbrev' => 'CD',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 57,
                'gym_id' => 8,
                'name' => 'Trampoline',
                'abbrev' => 'TP',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 58,
                'gym_id' => 8,
                'name' => 'Tumbling',
                'abbrev' => 'TB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 59,
                'gym_id' => 8,
                'name' => 'Stunting',
                'abbrev' => 'ST',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 60,
                'gym_id' => 8,
                'name' => 'Double Mini',
                'abbrev' => 'DM',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 61,
                'gym_id' => 8,
                'name' => 'Power Tumbling',
                'abbrev' => 'PT',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 62,
                'gym_id' => 8,
                'name' => 'Motions',
                'abbrev' => 'MO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 63,
                'gym_id' => 8,
                'name' => 'Jumps',
                'abbrev' => 'JP',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 64,
                'gym_id' => 8,
                'name' => 'Locomotor',
                'abbrev' => 'LO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 65,
                'gym_id' => 8,
                'name' => 'Warm Up',
                'abbrev' => 'WU',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 66,
                'gym_id' => 8,
                'name' => 'Handstands',
                'abbrev' => 'HND',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 67,
                'gym_id' => 8,
                'name' => 'Cartwheels',
                'abbrev' => 'CRT',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 68,
                'gym_id' => 8,
                'name' => 'Rolls',
                'abbrev' => 'RLS',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 69,
                'gym_id' => 8,
                'name' => 'Stretch & Shapes',
                'abbrev' => 'S&S',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 70,
                'gym_id' => 8,
                'name' => 'Bridging',
                'abbrev' => 'BRD',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 71,
                'gym_id' => 8,
                'name' => '1 Warm Up',
                'abbrev' => 'WMU',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 72,
                'gym_id' => 8,
                'name' => '2 Stretch',
                'abbrev' => 'STR',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 73,
                'gym_id' => 8,
                'name' => '3 Handstands',
                'abbrev' => 'HNS',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 74,
                'gym_id' => 8,
                'name' => '4 Cartwheels',
                'abbrev' => 'CRW',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 75,
                'gym_id' => 8,
                'name' => '5 Rolls',
                'abbrev' => 'ROL',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 76,
                'gym_id' => 8,
                'name' => '6 Bridging',
                'abbrev' => 'BRG',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 77,
                'gym_id' => 8,
                'name' => '7 Conditioning',
                'abbrev' => 'CND',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 78,
                'gym_id' => 8,
                'name' => '3 Jumps',
                'abbrev' => 'JMP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 79,
                'gym_id' => 8,
                'name' => '4 Handstands',
                'abbrev' => 'HAN',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 80,
                'gym_id' => 8,
                'name' => '5 Cartwheels',
                'abbrev' => 'CAR',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 81,
                'gym_id' => 8,
                'name' => '6 Rolls',
                'abbrev' => 'ROL',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 82,
                'gym_id' => 8,
                'name' => '7 Bridging',
                'abbrev' => 'BRI',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 83,
                'gym_id' => 8,
                'name' => '8 Conditioning',
                'abbrev' => 'CON',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 84,
                'gym_id' => 2,
                'name' => 'Vault',
                'abbrev' => 'VT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 85,
                'gym_id' => 2,
                'name' => 'Bars',
                'abbrev' => 'UB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 86,
                'gym_id' => 2,
                'name' => 'Beam',
                'abbrev' => 'BB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 87,
                'gym_id' => 2,
                'name' => 'Floor',
                'abbrev' => 'FX',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 88,
                'gym_id' => 2,
                'name' => 'Pommel',
                'abbrev' => 'PH',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 89,
                'gym_id' => 2,
                'name' => 'Rings',
                'abbrev' => 'SR',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 90,
                'gym_id' => 2,
                'name' => 'PBars',
                'abbrev' => 'PB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 91,
                'gym_id' => 2,
                'name' => 'HBar',
                'abbrev' => 'HB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 92,
                'gym_id' => 2,
                'name' => 'Conditioning',
                'abbrev' => 'CD',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 93,
                'gym_id' => 2,
                'name' => 'Trampoline',
                'abbrev' => 'TP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 94,
                'gym_id' => 2,
                'name' => 'Tumbling',
                'abbrev' => 'TB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 95,
                'gym_id' => 2,
                'name' => 'Stunting',
                'abbrev' => 'ST',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 96,
                'gym_id' => 2,
                'name' => 'Double Mini',
                'abbrev' => 'DM',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 97,
                'gym_id' => 2,
                'name' => 'Power Tumbling',
                'abbrev' => 'PT',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 98,
                'gym_id' => 2,
                'name' => 'Motions',
                'abbrev' => 'MO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 99,
                'gym_id' => 2,
                'name' => 'Jumps',
                'abbrev' => 'JP',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 100,
                'gym_id' => 2,
                'name' => 'Locomotor',
                'abbrev' => 'LO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 101,
                'gym_id' => 2,
                'name' => 'Warm Up',
                'abbrev' => 'WU',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 102,
                'gym_id' => 2,
                'name' => 'Tumbletrak',
                'abbrev' => 'TT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 103,
                'gym_id' => 2,
                'name' => 'Flexibility',
                'abbrev' => 'FL',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 104,
                'gym_id' => 1,
                'name' => 'Vault',
                'abbrev' => 'VT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 105,
                'gym_id' => 1,
                'name' => 'Bars',
                'abbrev' => 'UB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 106,
                'gym_id' => 1,
                'name' => 'Beam',
                'abbrev' => 'BB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 107,
                'gym_id' => 1,
                'name' => 'Floor',
                'abbrev' => 'FX',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 108,
                'gym_id' => 1,
                'name' => 'Pommel',
                'abbrev' => 'PH',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 109,
                'gym_id' => 1,
                'name' => 'Rings',
                'abbrev' => 'SR',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 110,
                'gym_id' => 1,
                'name' => 'PBars',
                'abbrev' => 'PB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 111,
                'gym_id' => 1,
                'name' => 'HBar',
                'abbrev' => 'HB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 112,
                'gym_id' => 1,
                'name' => 'Conditioning',
                'abbrev' => 'CD',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 113,
                'gym_id' => 1,
                'name' => 'Trampoline',
                'abbrev' => 'TP',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 114,
                'gym_id' => 1,
                'name' => 'Tumbling',
                'abbrev' => 'TB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 115,
                'gym_id' => 1,
                'name' => 'Stunting',
                'abbrev' => 'ST',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 116,
                'gym_id' => 1,
                'name' => 'Double Mini',
                'abbrev' => 'DM',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 117,
                'gym_id' => 1,
                'name' => 'Power Tumbling',
                'abbrev' => 'PT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 118,
                'gym_id' => 1,
                'name' => 'Motions',
                'abbrev' => 'MO',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 119,
                'gym_id' => 1,
                'name' => 'Jumps',
                'abbrev' => 'JP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 120,
                'gym_id' => 1,
                'name' => 'Locomotor',
                'abbrev' => 'LO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 121,
                'gym_id' => 1,
                'name' => 'Warm Up',
                'abbrev' => 'WU',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 122,
                'gym_id' => 1,
                'name' => 'Dance',
                'abbrev' => 'DA',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 123,
                'gym_id' => 1,
                'name' => 'Synchro',
                'abbrev' => 'SY',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 124,
                'gym_id' => 1,
                'name' => 'Ninja Track',
                'abbrev' => 'NJ',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 125,
                'gym_id' => 1,
                'name' => 'Stall Bars',
                'abbrev' => 'SB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 126,
                'gym_id' => 1,
                'name' => 'Bars Conditioning',
                'abbrev' => 'BC',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 127,
                'gym_id' => 1,
                'name' => 'Ninja Rings',
                'abbrev' => 'NR',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 128,
                'gym_id' => 1,
                'name' => 'Toddlers balls',
                'abbrev' => 'TBA',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 129,
                'gym_id' => 1,
                'name' => 'Stretching',
                'abbrev' => 'STR',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 130,
                'gym_id' => 1,
                'name' => 'Vault Conditioning',
                'abbrev' => 'VC',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 131,
                'gym_id' => 1,
                'name' => 'Tumble Track',
                'abbrev' => 'TT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 132,
                'gym_id' => 3,
                'name' => 'Vault',
                'abbrev' => 'VT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 133,
                'gym_id' => 3,
                'name' => 'Bars',
                'abbrev' => 'UB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 134,
                'gym_id' => 3,
                'name' => 'Beam',
                'abbrev' => 'BB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 135,
                'gym_id' => 3,
                'name' => 'Floor',
                'abbrev' => 'FX',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 136,
                'gym_id' => 3,
                'name' => 'Pommel',
                'abbrev' => 'PH',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 137,
                'gym_id' => 3,
                'name' => 'Rings',
                'abbrev' => 'SR',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 138,
                'gym_id' => 3,
                'name' => 'PBars',
                'abbrev' => 'PB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 139,
                'gym_id' => 3,
                'name' => 'HBar',
                'abbrev' => 'HB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 140,
                'gym_id' => 3,
                'name' => 'Conditioning',
                'abbrev' => 'CD',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 141,
                'gym_id' => 3,
                'name' => 'Trampoline',
                'abbrev' => 'TP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 142,
                'gym_id' => 3,
                'name' => 'Tumbling',
                'abbrev' => 'TB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 143,
                'gym_id' => 3,
                'name' => 'Stunting',
                'abbrev' => 'ST',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 144,
                'gym_id' => 3,
                'name' => 'Double Mini',
                'abbrev' => 'DM',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 145,
                'gym_id' => 3,
                'name' => 'Power Tumbling',
                'abbrev' => 'PT',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 146,
                'gym_id' => 3,
                'name' => 'Motions',
                'abbrev' => 'MO',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 147,
                'gym_id' => 3,
                'name' => 'Jumps',
                'abbrev' => 'JP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 148,
                'gym_id' => 3,
                'name' => 'Locomotor',
                'abbrev' => 'LO',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 149,
                'gym_id' => 3,
                'name' => 'Warm Up',
                'abbrev' => 'WU',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 150,
                'gym_id' => 5,
                'name' => 'Vault',
                'abbrev' => 'VT',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 151,
                'gym_id' => 5,
                'name' => 'Bars',
                'abbrev' => 'UB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 152,
                'gym_id' => 5,
                'name' => 'Beam',
                'abbrev' => 'BB',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 153,
                'gym_id' => 5,
                'name' => 'Floor',
                'abbrev' => 'FX',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 154,
                'gym_id' => 5,
                'name' => 'Pommel',
                'abbrev' => 'PH',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 155,
                'gym_id' => 5,
                'name' => 'Rings',
                'abbrev' => 'SR',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 156,
                'gym_id' => 5,
                'name' => 'PBars',
                'abbrev' => 'PB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 157,
                'gym_id' => 5,
                'name' => 'HBar',
                'abbrev' => 'HB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 158,
                'gym_id' => 5,
                'name' => 'Conditioning',
                'abbrev' => 'CD',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 159,
                'gym_id' => 5,
                'name' => 'Trampoline',
                'abbrev' => 'TP',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 160,
                'gym_id' => 5,
                'name' => 'Tumbling',
                'abbrev' => 'TB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 161,
                'gym_id' => 5,
                'name' => 'Stunting',
                'abbrev' => 'ST',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 162,
                'gym_id' => 5,
                'name' => 'Double Mini',
                'abbrev' => 'DM',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 163,
                'gym_id' => 5,
                'name' => 'Power Tumbling',
                'abbrev' => 'PT',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 164,
                'gym_id' => 5,
                'name' => 'Motions',
                'abbrev' => 'MO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 165,
                'gym_id' => 5,
                'name' => 'Jumps',
                'abbrev' => 'JP',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 166,
                'gym_id' => 5,
                'name' => 'Locomotor',
                'abbrev' => 'LO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 167,
                'gym_id' => 5,
                'name' => 'Warm Up',
                'abbrev' => 'WU',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 168,
                'gym_id' => 4,
                'name' => 'Bars Conditioning',
                'abbrev' => 'BC',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 169,
                'gym_id' => 4,
                'name' => 'Stall Bars',
                'abbrev' => 'SB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 170,
                'gym_id' => 4,
                'name' => 'Ninja Track',
                'abbrev' => 'NJ',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 171,
                'gym_id' => 4,
                'name' => 'Motions',
                'abbrev' => 'MO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 172,
                'gym_id' => 4,
                'name' => 'Locomotor',
                'abbrev' => 'LO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 173,
                'gym_id' => 4,
                'name' => 'Warm Up',
                'abbrev' => 'WU',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 174,
                'gym_id' => 4,
                'name' => 'Jumps',
                'abbrev' => 'JP',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 175,
                'gym_id' => 4,
                'name' => 'Dance',
                'abbrev' => 'DA',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 176,
                'gym_id' => 6,
                'name' => 'Locomotor',
                'abbrev' => 'LO',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 177,
                'gym_id' => 6,
                'name' => 'Jumps',
                'abbrev' => 'JP',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 178,
                'gym_id' => 6,
                'name' => 'Stall Bars',
                'abbrev' => 'SB',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 179,
                'gym_id' => 6,
                'name' => 'Warm Up',
                'abbrev' => 'WU',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 180,
                'gym_id' => 6,
                'name' => 'Ninja Track',
                'abbrev' => 'NJ',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 181,
                'gym_id' => 6,
                'name' => 'Motions',
                'abbrev' => 'MO',
                'deleted_at' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 182,
                'gym_id' => 6,
                'name' => 'Dance',
                'abbrev' => 'DA',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 183,
                'gym_id' => 6,
                'name' => 'Bars Conditioning',
                'abbrev' => 'BC',
                'deleted_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
       
        DB::statement('ALTER SEQUENCE events_id_seq RESTART WITH 184;');
    }
}
